"use client";

interface Props {
  recommendations?: string[];
}

export default function AIRecommendations({
  recommendations = [],
}: Props) {
  return (
    <section className="rounded-3xl border border-gray-800 bg-gradient-to-br from-[#0F172A] to-black p-8">

      <div className="mb-8">

        <h2 className="text-3xl font-bold">
          AI Recommendations
        </h2>

        <p className="mt-2 text-gray-400">
          Personalized improvements generated by DevScope AI
        </p>

      </div>

      <div className="grid gap-5">

        {recommendations.map((item, index) => (

          <div
            key={index}
            className="group flex items-start gap-5 rounded-2xl border border-gray-800 bg-gradient-to-r from-gray-900 to-[#111827] p-6 transition-all duration-300 hover:-translate-y-1 hover:border-violet-500/40 hover:shadow-[0_0_25px_rgba(139,92,246,0.18)]"
          >

            <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-violet-500/15 text-2xl">
              💡
            </div>

            <div className="flex-1">

              <h3 className="font-semibold text-white">
                Recommendation {index + 1}
              </h3>

              <p className="mt-2 leading-7 text-gray-300">
                {item}
              </p>

            </div>

            <div className="rounded-full bg-green-500/20 px-3 py-1 text-sm font-medium text-green-300">
              Suggested
            </div>

          </div>

        ))}

      </div>

    </section>
  );
}