import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { AnalysisResult } from "@/types/repository";

function cleanMarkdown(text: string): string {
  return text
    .replace(/^#{1,6}\s/gm, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`/g, "")
    .replace(/^---$/gm, "")
    .replace(/\|/g, " ")
    .replace(/\r/g, "")
    .trim();
}

export function exportPDF(result: AnalysisResult) {
  const doc = new jsPDF();

  // ==========================
  // Header
  // ==========================

  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, 210, 35, "F");

  doc.setTextColor(255);

  doc.setFontSize(24);
  doc.text("DevScope AI", 14, 18);

  doc.setFontSize(12);
  doc.text(
    "Repository Intelligence Report",
    14,
    28
  );

  doc.setTextColor(30);

  // ==========================
  // Repository Information
  // ==========================

  doc.setFontSize(18);
  doc.text("Repository Information", 14, 48);

  autoTable(doc, {
    startY: 55,

    head: [["Property", "Value"]],

    body: [
      ["Repository", result.repository_info.name],
      ["Owner", result.repository_info.owner],
      ["Language", result.repository_info.language],
      ["Stars", String(result.repository_info.stars)],
      ["Forks", String(result.repository_info.forks)],
      [
        "Updated",
        new Date(
          result.repository_info.updated
        ).toLocaleDateString(),
      ],
    ],

    headStyles: {
      fillColor: [124, 58, 237],
    },

    styles: {
      fontSize: 10,
    },
  });

  // ==========================
  // Scores
  // ==========================

  autoTable(doc, {
    startY:
      (doc as any).lastAutoTable.finalY + 12,

    head: [["Metric", "Score"]],

    body: [
      [
        "Project Health",
        `${result.scores.project_health}%`,
      ],

      [
        "Security",
        `${result.scores.security}%`,
      ],

      [
        "Architecture",
        `${result.scores.architecture}%`,
      ],

      [
        "Maintainability",
        `${result.scores.maintainability}%`,
      ],
    ],

    headStyles: {
      fillColor: [124, 58, 237],
    },

    styles: {
      fontSize: 10,
    },
  });

  // ==========================
  // Recommendations
  // ==========================

  let y =
    (doc as any).lastAutoTable.finalY + 15;

  doc.setFontSize(18);
  doc.text("Recommendations", 14, y);

  y += 8;

  doc.setFontSize(11);

  result.recommendations?.forEach((item) => {
    const lines = doc.splitTextToSize(
      "• " + item,
      180
    );

    if (y > 270) {
      doc.addPage();
      y = 20;
    }

    doc.text(lines, 18, y);

    y += lines.length * 6 + 4;
  });

  // ==========================
  // AI Analysis
  // ==========================

  y += 10;

  if (y > 260) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(18);
  doc.text("DevScope AI Analysis", 14, y);

  y += 10;

  const cleanedReport = cleanMarkdown(
    result.ai_analysis
  );

  const reportLines = doc.splitTextToSize(
    cleanedReport,
    180
  );

  doc.setFontSize(10);

  for (const line of reportLines) {
  if (y > 280) {
    doc.addPage();

    y = 20;

    doc.setFontSize(10);
  }

  // Section headings
  if (
    line === "Project Overview" ||
    line === "Technology Stack" ||
    line === "Repository Metrics" ||
    line === "Architecture" ||
    line === "Code Quality" ||
    line === "Security" ||
    line === "Performance" ||
    line === "Recommendations"
  ) {
    y += 4;

    doc.setFontSize(16);
    doc.setTextColor(124, 58, 237);

    doc.text(line, 14, y);

    y += 8;

    doc.setFontSize(10);
    doc.setTextColor(30);

    continue;
  }

  // Sub-headings
  if (
    line.endsWith("Layer") ||
    line.endsWith("Layer:")
  ) {
    y += 2;

    doc.setFontSize(13);

    doc.setTextColor(70);

    doc.text(line, 14, y);

    y += 7;

    doc.setFontSize(10);

    doc.setTextColor(30);

    continue;
  }

  // Bullet formatting
  if (
    line.startsWith("-") ||
    line.startsWith("•")
  ) {
    doc.text(
      "• " + line.replace(/^[-•]\s*/, ""),
      18,
      y
    );
  } else {
    doc.text(line, 14, y);
  }

  y += 6;
}

// ==========================
// Footer
// ==========================

const pages = doc.getNumberOfPages();

for (let i = 1; i <= pages; i++) {
  doc.setPage(i);

  doc.setDrawColor(220);
  doc.line(14, 287, 196, 287);

  doc.setFontSize(9);

  doc.setTextColor(120);

  doc.text(
    "Generated by DevScope AI",
    14,
    293
  );

  doc.text(
    `Page ${i} of ${pages}`,
    175,
    293
  );
}

doc.save(
  `${result.repository_info.name}_DevScope_Report.pdf`
);
}