"use client";

import {
  Star,
  GitFork,
  Calendar,
  ExternalLink,
  Code2,
} from "lucide-react";

interface Props {
  repository: {
    name: string;
    owner: string;
    language: string;
    stars: number;
    forks: number;
    updated: string;
    description?: string;
  };

  repoUrl: string;

  onDownload: () => void;
}

export default function RepositoryHero({
  repository,
  repoUrl,
  onDownload,
}: Props) {
  return (
    <section className="overflow-hidden rounded-3xl border border-gray-800 bg-gradient-to-br from-[#111827] via-[#1E1B4B] to-[#0F172A] shadow-2xl">

      <div className="flex flex-col gap-8 p-8 lg:flex-row lg:items-center lg:justify-between">

        <div className="space-y-5">

          <div className="flex items-center gap-4">

            <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-violet-600">

              <Code2 size={34} />

            </div>

            <div>

              <h2 className="text-4xl font-bold">

                {repository.name}

              </h2>

              <p className="text-gray-400">

                by {repository.owner}

              </p>

            </div>

          </div>

          <p className="max-w-3xl text-gray-300">

            {repository.description ||
              "AI-powered repository intelligence generated by DevScope AI."}

          </p>

                    <div className="flex flex-wrap gap-4">

            <div className="flex items-center gap-2 rounded-full border border-gray-700 bg-gray-900 px-4 py-2">

              <Star
                size={18}
                className="text-yellow-400"
              />

              <span>{repository.stars}</span>

            </div>

            <div className="flex items-center gap-2 rounded-full border border-gray-700 bg-gray-900 px-4 py-2">

              <GitFork
                size={18}
                className="text-blue-400"
              />

              <span>{repository.forks}</span>

            </div>

            <div className="rounded-full border border-gray-700 bg-gray-900 px-4 py-2">

              💻 {repository.language}

            </div>

            <div className="flex items-center gap-2 rounded-full border border-gray-700 bg-gray-900 px-4 py-2">

              <Calendar
                size={16}
                className="text-green-400"
              />

              <span>

                {new Date(
                  repository.updated
                ).toLocaleDateString()}

              </span>

            </div>

          </div>

        </div>

        <div className="flex flex-col gap-4">

          <a
            href={repoUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center gap-2 rounded-xl bg-violet-600 px-6 py-3 font-semibold transition hover:bg-violet-500"
          >

            <ExternalLink size={18} />

            Open GitHub

          </a>

          <button
            onClick={onDownload}
            className="rounded-xl border border-violet-500 px-6 py-3 font-semibold transition hover:bg-violet-600"
          >

            Download Report

          </button>

        </div>

      </div>

    </section>
  );
}